/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdint.h"

typedef volatile unsigned int vint32_t;

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR		*(volatile uint32_t*)(RCC_BASE + 0x18)

//GPIOA
#define GPIOA_BASE		0x40010800
#define GPIOA_CRL		*(volatile uint32_t*)(GPIOA_BASE + 0x00)
#define GPIOA_CRH		*(volatile uint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t*)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR		*(volatile uint32_t*)(GPIOA_BASE + 0x08)

//GPIOB
#define GPIOB_BASE		0x40010C00
#define GPIOB_CRL		*(volatile uint32_t*)(GPIOB_BASE + 0x00)
#define GPIOB_CRH		*(volatile uint32_t*)(GPIOB_BASE + 0x04)
#define GPIOB_ODR		*(volatile uint32_t*)(GPIOB_BASE + 0x0C)
#define GPIOA_IDR		*(volatile uint32_t*)(GPIOA_BASE + 0x08)

#define GPIOB1	(1UL<<1)
#define GPIOB13 (1UL<<13)

void clock_init()
{
	//Enable RCC CLK to GPIOA, bit2
	RCC_APB2ENR |= 1<<2;
	//Enable RCC CLK to GPIOB, bit3
	RCC_APB2ENR |= 1<<3;
}
void GPIO_init()
{
	//GPIOA
	GPIOA_CRL = 0x0; //as reset value is Reset value: 0x4444 4444 and not 0
	GPIOA_CRH = 0x0;

	//PA1 i/p high Z mode
	//CNF 01: Floating input (reset state)
	GPIOA_CRL |=(0b01<<6);
	//MODE 00: Input mode (reset state)
	GPIOB_CRL &= ~(0b11<<4);


	//PA13 i/p high Z mode
	//CNF 01: Floating input (reset state)
	GPIOA_CRH &=~(0b00<<20);
	//MODE 00: Input mode (reset state)
	GPIOA_CRH |=(0b01<<22);



	//GPIOB
	GPIOB_CRL = 0x0; //as reset value is Reset value: 0x4444 4444 and not 0
	GPIOB_CRH = 0x0;

	//PB1 o/p  push pull mode
	//CNF 00: General purpose output push-pull
	GPIOB_CRL &= ~(0b11<<6);
	//MODE 01: Output mode, max speed 10 MHz
	GPIOB_CRL |= (0b01<<4);

	//PB13 o/p  push pull mode
	//CNF 00: General purpose output push-pull
	GPIOB_CRH &= ~(0b11<<22);
	//MODE 01: Output mode, max speed 10 MHz
	GPIOB_CRH |= (0b01<<20);

}

void wait(int x)
{
	unsigned int i,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}
int main (void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		//PA1 >> conn to ext PUR so by default value = 1 (VCC) , PB > 0 (GND)
		if (((GPIOA_IDR & (1<<1)) >> 1) == 0) //Read IDR pin1
		{
			GPIOB_ODR ^= (1<<1); //toggle PB1
			while(((GPIOA_IDR & (1<<1)) >> 1) == 0); //Single Press
		}
		//PA13 >> conn to ext PUD so by default value = 0 (GND),  PB > 1 (VCC)
		if (((GPIOA_IDR & (1<<13)) >> 13) == 1) //Read IDR pin1
		{
			GPIOB_ODR ^= (1<<13); //toggle PB1
		}
		wait(1);
	}
	return 0;
}

