/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdint.h"

typedef volatile unsigned int vint32_t;

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR		*(volatile uint32_t*)(RCC_BASE + 0x18)

//GPIO
#define PORTA_BASE 0x40010800
#define GPIOA_CRL		*(volatile uint32_t*)(PORTA_BASE + 0x00)
#define GPIOA_CRH		*(volatile uint32_t*)(PORTA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t*)(PORTA_BASE + 0x0C)

//EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR		*(volatile uint32_t*)(EXTI_BASE + 0x00)
#define EXTI_RTSR		*(volatile uint32_t*)(EXTI_BASE + 0x08)
#define EXTI_PR			*(volatile uint32_t*)(EXTI_BASE + 0x14)


//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1		*(volatile uint32_t*)(AFIO_BASE + 0x08)

#define NVIC_ISER0		*(volatile uint32_t*)(0xE000E100)

typedef union {
	vint32_t all_fields;
	struct {
		vint32_t reserved:13;
		vint32_t pin13:1;

	}pin;

}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(PORTA_BASE + 0x0C);

void clock_init()
{
	RCC_APB2ENR |= 1<<2; //enable RCC CLK to GPIOA, bit 2

	//Bit 0 AFIOEN: Alternate function I/O clock enable
	RCC_APB2ENR |= (1<<0);
}
void GPIO_init()
{
	//Set PIN13 in PORTA as Output
	GPIOA_CRH &=0xFF0FFFFF; //clear 20 to 24
	GPIOA_CRH |=0x00200000; //write 2

	//PINA0 : 01 : Floating i/p reset state
	GPIOA_CRL |= (1<<2);

}

int main (void)
{
	clock_init();
	GPIO_init();

	//EXTI x config (x=0) to PORTA0
	AFIO_EXTICR1 = 0;

	//Enable rising edge for line 0
	EXTI_RTSR |= (1<<0);

	//enable external interrupt line 0 >> mask = 1
	EXTI_IMR |= (1<<0);

	//enable NVIC IRQ 6 <<>> EXTI0
	NVIC_ISER0 |= (1<<6);


	while(1);
	return 0;
}

void EXTI0_IRQHandler (void)
{
	//IRQ occurred to EXTI0 >> PORTA PIN 0 >> rising edge
	//toggle led pin A 13
	GPIOA_ODR ^= (1<<13);

	//Clear Pending Request Register for Line 0
	EXTI_PR |= (1<<0);

}

